//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacione
    {
        public int Id { get; set; }
        public string Nombre_Empleado { get; set; }
        public string Desde { get; set; }
        public string Hasta { get; set; }
        public System.DateTime Correspondiente_a_Ano { get; set; }
        public string Comentarios { get; set; }
    }
}
